### ISSUE TITLE
Typo in MediaTrackConstraintSet

### ISSUE THREAD

**Issue by sk-** [Microsoft/TSJS-lib-generator#285] opened 2017-08-23 03:01 UTC
Instead of `echoCancelation` the field should be called `echoCancellation` as per the spec https://w3c.github.io/mediacapture-main/getusermedia.html#media-track-constraints

**Comment by mhegazy** [comment] 2017-08-23 17:42
A PR would be appreciated.

**Comment by chris-morgan** [comment] 2017-09-16 10:26
Duplicate of #251.

**Comment by saschanaz** [comment] 2018-04-28 16:17
This is fixed now.

**Closed** 2018-04-30 16:37 UTC
